[build]
builder = "dockerfile"

[deploy]
startCommand = "docker run -d -p 80:80 --name kumite kumite"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10